export const LinkActionTypes = {
  SET_LINKS: 'SET_LINKS',
  UPDATE_LINK_PENDING: 'UPDATE_LINK_PENDING',
  REMOVE_LINK_PENDING: 'REMOVE_LINK_PENDING',
  ADD_LINK_PENDING: 'ADD_LINK_PENDING',
  GET_LINKS_PENDING: 'GET_LINKS_LOADING',
  SET_ERROR: 'SET_ERROR'
};
